version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres   # Use the new Dockerfile for PostgreSQL
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: event
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile   # Use the existing Dockerfile for the Spring Boot app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/event
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data:
