spring:
  thymeleaf:
    prefix: "classpath:/templates/:"
    cache: false
  web:
    resources:
      cache:
        period: 0
      static-locations: file:src/main/resources/static/

  jpa:
    generate-ddl: true
#    defer-datasource-initialization: true
  application:
    name: events
  datasource:
    url: jdbc:postgresql://localhost:5432/event
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: event_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS event_schema
      connection-timeout: 10000
#  sql:
#    init:
#      mode:
#        always
  mail:
    host: smtp.gmail.com
    port: 587
    username: iac.spb.events@gmail.com
    password: ylyalyxoujomkqgk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG